<?php

$peImage = "https://peprojects.dev/images/landscape.jpg";

$cakeData = [
	[
		"id" => 0,
		"name" => "A Smashing 1st Birthday",
		"pictureURL" => "images/smash-cake.jpg",
		"date" => "Aug 2019",
		"story" => "Ani and Ami's 1st first birthday complete with two mini-smash cakes.",
		"composition" => [
			"Sponge" => "funfetti",
			"Filling" => "cream cheese",
			"Texture" => "vanilla cookie crumbs",
			"Soak"  => "vanilla milk",
			"Outer Frosting" => "cream cheese buttercream",
			"Decorations" => "cakepops",
		],
	],
	[
		"id" => 1,
		"name" => "Liquid Luck",
		"pictureURL" => "images/liquid-luck.jpg",
		"date" => "Mar 2020",
		"story" => "Gotta go green if your birthday is on St Patty's Day!",
		"composition" => [
			"Sponge" => "mint chocolate chip",
			"Filling" => "mint vanilla buttercream",
			"Texture" => "vanilla cookie crumbs",
			"Soak" => "peppermint milk",
			"Outer Frosting" => "vanilla swiss meringue buttercream",
			"Decorations" => "dark choclate drip, mint chocolate macarons",
		],
	],
	[
		"id" => 2,
		"name" => "Love is sweet... and sour🍋",
		"pictureURL" => "images/lemon-cake.jpg",
		"date" => "Aug 2020",
		"story" => "A little surprise from wife to husband",
		"composition" => [
			"Sponge" => "lemon",
			"Filling" => "lemon curd",
			"Texture" => "vanilla cookie crumbs",
			"Soak" => "limoncello",
			"Outer Frosting" => "lemon swiss meringue buttercream",
			"Decorations" => "lemon macarons, birthday sprinkles",
		],
	],
	[
		"id" => 3,
		"name" => "The Maroon Swoon",
		"pictureURL" => "images/daniels-wedding.jpg",
		"date" => "Oct 2020",
		"story" => "3 tiers of different cake flavors for these Nashville sweethearts",
		"composition" => [
			"Sponge" => "(1) toasted vanilla, (2) strawberry, (3) double Chocolate",
			"Filling" => "(1) cinnamon pecan custard, (2) strawberry, (3) vanilla mascarpone",
			"Texture" => "(1) toasted pecans, (2) shortbread crumbs, (3) biscoff cookie crumbs",
			"Soak" => "(1) bourbon syrup, (2) sparkling rose syrup, (3) Amaretto coffee liqueur",
			"Outer Frosting" => "vanilla swiss meringue buttercream",
			"Decorations" => "salted caramel macarons, red flowers, maroon ribbon, gold topper",
		],
	],
	[
		"id" => 4,
		"name" => "Cookie Monster-In-Law",
		"pictureURL" => "images/chocolate-cookie.jpg",
		"date" => "Nov 2020",
		"story" => "A death-by-chocolate-surprise to win over a mother-in-law",
		"composition" => [
			"Sponge" => "triple chocolate",
			"Filling" => "fudge cream",
			"Texture" => "oreo cookie",
			"Soak" => "hot chocolate",
			"Outer Frosting" => "chocolate marshmallow buttercream",
			"Decorations" => "chocolate specks, homemade chocolate chip cookies",
		],
	],
	[
		"id" => 5,
		"name" => "BoHo Pop Wedding",
		"pictureURL" => "images/tyson-hagar-wedding.jpg",
		"date" => "Mar 2021",
		"story" => "Whatever the bride wants, she gets! A statement moedern piece contrasting soft earthy tones",
		"composition" => [
			"Sponge" => "(1) spice cake, (2) lemon",
			"Filling" => "(1) dulce de leche custard, (2) lemon curd",
			"Texture" => "(1) gingerbread crumbs, (2) vanilla cookie crumbs",
			"Soak" => "(1) chai, (2) limoncello",
			"Outer Frosting" => "vanilla swiss meringue buttercream",
			"Decorations" => "buttercream paintstrokes, orchids",
		],
	],
	[
		"id" => 6,
		"name" => "Riding off into the Sunset",
		"pictureURL" => "images/riding.jpg",
		"date" => "Mar 2021",
		"story" => "A first - a creation with figurines of miniature horses",
		"composition" => [
			"Sponge" => "checkered triple chocolate and funfetti vanilla",
			"Filling" => "vanilla swiss meringue buttercream",
			"Texture" => "vanilla and chocoalte cookie crumbs",
			"Soak" => "None",
			"Outer Frosting" => "vanilla swiss meringue buttercream",
			"Decorations" => "horse figurines, vanilla macarons, gold paint splashs, gold tinted sails",
		],
	],
		[
		"id" => 7,
		"name" => "A Wedding by Any Other Name Would Smell as Sweet",
		"pictureURL" => "images/rose-wedding.jpg",
		"date" => "Jun 2021",
		"story" => "A COVID wedding calls for a smaller but elegant cake!",
		"composition" => [
			"Sponge" => "red velvet",
			"Filling" => "cream cheese buttercream",
			"Texture" => "oreo cookie crumbs",
			"Soak" => "hot chocolate soak",
			"Outer Frosting" => "vanilla swiss buttercream",
			"Decorations" => "roses",
		],
	],
	[
		"id" => 8,
		"name" => "Fab Forty",
		"pictureURL" => "images/rainbow.jpg",
		"date" => "Apr 2022",
		"story" => "Whimsical and delcious meet for a big gay birthday",
		"composition" => [
			"Sponge" => "funfetti",
			"Filling" => "cream cheese buttercream",
			"Texture" => "vanilla cookies crumbs",
			"Soak" => "vanila milk",
			"Outer Frosting" => "cream cheese buttercream",
			"Decorations" => "exposed rainbow stripe and rainbow candy",
		],
	],

	[
		"id" => 9,
		"name" => "Simple and sweet (and&nbspsmall)",
		"pictureURL" => "images/cupcakes.jpg",
		"date" => "July 2022",
		"story" => "Even small gatherings need need celebration cake!",
		"composition" => [
			"Sponge" => "spice",
			"Filling" => "None",
			"Texture" => "None",
			"Soak" => "spiced rum syrup",
			"Outer Frosting" => "cream cheese buttercream",
			"Decorations" => "minimalistic and modern buttercream piping",
		],
	],

	[
		"id" => 10,
		"name" => "Oh Hey, Ojai",
		"pictureURL" => "images/ojai.jpg",
		"date" => "Oct 2022",
		"story" => "A fall festive treat for a wedding in the quaint town of Ojai",
		"composition" => [
			"Sponge" => "chai spice",
			"Filling" => "whipped burbon salted caramel and cream cheese buttercream",
			"Texture" => "vanilla cookie crumbs",
			"Soak" => "spiced rum syrup",
			"Outer Frosting" => "vanilla swiss meringue buttercream",
			"Decorations" => "boho-style plants",
		],
	],
];